version: '3'
services:
  ponger:
    container_name: ponger
    build: ./ponger
    ports:
      - 8080:8080
    networks:
      - service

  pinger:
    container_name: pinger
    build: ./pinger
    depends_on:
      - ponger
    networks:
      - service

networks:
  service:
    driver: bridge
